# Generated by Django 3.2.9 on 2021-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues_to_the_department', models.CharField(max_length=200)),
                ('fees_for_the_hospital_and_bookshop', models.FloatField()),
                ('charges_for_damage', models.IntegerField()),
                ('returns_all_athletic_gear', models.BooleanField(default=True)),
                ('Dues_to_the_student_union', models.CharField(max_length=200)),
                ('Male_deal_approal', models.BooleanField(default=True)),
                ('obtaining_secutity_chance', models.CharField(max_length=200)),
            ],
        ),
    ]
