# Generated by Django 3.2.9 on 2021-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examsrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('passed', models.BooleanField(default=True)),
                ('year_of_gap', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
